from __future__ import annotations

from dataclasses import fields
from typing import TypeAlias

from app.models import CompanyRecord, JobRecord, JobUpdateValue, SalaryRange


MOCK_COMPANIES: list[CompanyRecord] = [
    CompanyRecord(
        id="company-alphabet",
        name="Alphabet",
        description="Global technology company with products spanning search, cloud, developer tools, and AI.",
        website="https://abc.xyz",
        industry="Internet services and software",
        headquarters="Mountain View, CA",
        size="10000+",
        legal_name="Alphabet Inc.",
        address_line1="1600 Amphitheatre Parkway",
        address_line2="",
        city="Mountain View",
        region="CA",
        postal_code="94043",
        country="US",
        po_box="",
        phone="",
        contact_email="",
        location="Mountain View, CA, US",
        latitude=37.422,
        longitude=-122.0841,
        founded_year=2015,
        short_history="Alphabet was created in 2015 as the parent company of Google and its broader portfolio of technology businesses.",
    ),
    CompanyRecord(
        id="company-amazon",
        name="Amazon",
        description="Global technology company operating in e-commerce, cloud computing, devices, and digital services.",
        website="https://www.amazon.com",
        industry="E-commerce and cloud computing",
        headquarters="Seattle, WA",
        size="10000+",
        legal_name="Amazon.com, Inc.",
        address_line1="410 Terry Ave N",
        address_line2="",
        city="Seattle",
        region="WA",
        postal_code="98109",
        country="US",
        po_box="",
        phone="",
        contact_email="",
        location="Seattle, WA, US",
        latitude=47.6225,
        longitude=-122.3365,
        founded_year=1994,
        short_history="Amazon started as an online bookstore and expanded into a broad technology platform with AWS and large-scale consumer services.",
    ),
    CompanyRecord(
        id="company-meta",
        name="Meta Platforms",
        description="Technology company focused on social platforms, advertising, developer ecosystems, and AI.",
        website="https://about.meta.com",
        industry="Social media and advertising technology",
        headquarters="Menlo Park, CA",
        size="10000+",
        legal_name="Meta Platforms, Inc.",
        address_line1="1 Meta Way",
        address_line2="",
        city="Menlo Park",
        region="CA",
        postal_code="94025",
        country="US",
        po_box="",
        phone="",
        contact_email="",
        location="Menlo Park, CA, US",
        latitude=37.453,
        longitude=-122.1817,
        founded_year=2004,
        short_history="Meta began as Facebook and later rebranded to reflect its broader product portfolio beyond the flagship social network.",
    ),
    CompanyRecord(
        id="company-microsoft",
        name="Microsoft",
        description="Global software and cloud company spanning productivity products, developer platforms, AI, and enterprise infrastructure.",
        website="https://www.microsoft.com",
        industry="Software and cloud computing",
        headquarters="Redmond, WA",
        size="10000+",
        legal_name="Microsoft Corporation",
        address_line1="One Microsoft Way",
        address_line2="",
        city="Redmond",
        region="WA",
        postal_code="98052",
        country="US",
        po_box="",
        phone="",
        contact_email="",
        location="Redmond, WA, US",
        latitude=47.6396,
        longitude=-122.128,
        founded_year=1975,
        short_history="Microsoft grew from a PC software company into a major cloud, enterprise, productivity, and AI platform provider.",
    ),
    CompanyRecord(
        id="company-nvidia",
        name="NVIDIA",
        description="Technology company known for graphics, accelerated computing, AI hardware, and related software platforms.",
        website="https://www.nvidia.com",
        industry="Semiconductors and AI computing",
        headquarters="Santa Clara, CA",
        size="10000+",
        legal_name="NVIDIA Corporation",
        address_line1="2788 San Tomas Expressway",
        address_line2="",
        city="Santa Clara",
        region="CA",
        postal_code="95051",
        country="US",
        po_box="",
        phone="",
        contact_email="",
        location="Santa Clara, CA, US",
        latitude=37.3875,
        longitude=-121.9637,
        founded_year=1993,
        short_history="NVIDIA started in graphics processing and expanded into accelerated computing infrastructure for AI and data-intensive workloads.",
    ),
    CompanyRecord(
        id="company-jpmorgan-chase",
        name="JPMorgan Chase",
        description="Global financial services firm operating consumer banking, investment banking, markets, payments, and asset management businesses.",
        website="https://www.jpmorganchase.com",
        industry="Financial services",
        headquarters="New York, NY",
        size="10000+",
        legal_name="JPMorgan Chase & Co.",
        address_line1="270 Park Avenue",
        address_line2="",
        city="New York",
        region="NY",
        postal_code="10017",
        country="US",
        po_box="",
        phone="",
        contact_email="",
        location="New York, NY, US",
        latitude=40.7557,
        longitude=-73.9754,
        founded_year=2000,
        short_history="JPMorgan Chase combines banking institutions with roots going back more than two centuries and operates major global finance and markets businesses.",
    ),
    CompanyRecord(
        id="company-siemens",
        name="Siemens",
        description="Industrial technology company serving manufacturing, infrastructure, mobility, energy, automation, and digital industries.",
        website="https://www.siemens.com",
        industry="Industrial automation and infrastructure",
        headquarters="Munich, Germany",
        size="10000+",
        legal_name="Siemens AG",
        address_line1="Werner-von-Siemens-Strasse 1",
        address_line2="",
        city="Munich",
        region="Bavaria",
        postal_code="80333",
        country="Germany",
        po_box="",
        phone="",
        contact_email="",
        location="Munich, Germany",
        latitude=48.1351,
        longitude=11.582,
        founded_year=1847,
        short_history="Siemens began as a telegraph company and grew into a major industrial technology group focused on electrification, automation, and digitalization.",
    ),
    CompanyRecord(
        id="company-ing",
        name="ING",
        description="International bank offering retail banking, commercial banking, payments, lending, and financial markets services.",
        website="https://www.ing.com",
        industry="Banking and financial services",
        headquarters="Amsterdam, Netherlands",
        size="10000+",
        legal_name="ING Groep N.V.",
        address_line1="Bijlmerdreef 106",
        address_line2="",
        city="Amsterdam",
        region="North Holland",
        postal_code="1102 CT",
        country="Netherlands",
        po_box="",
        phone="",
        contact_email="",
        location="Amsterdam, Netherlands",
        latitude=52.3122,
        longitude=4.9487,
        founded_year=1991,
        short_history="ING was formed through the merger of Dutch insurance and banking groups and now operates a broad European and international banking platform.",
    ),
    CompanyRecord(
        id="company-booking",
        name="Booking.com",
        description="Online travel company connecting travelers with hotels, homes, flights, rental cars, attractions, and other travel services.",
        website="https://www.booking.com",
        industry="Travel and hospitality",
        headquarters="Amsterdam, Netherlands",
        size="10000+",
        legal_name="Booking.com B.V.",
        address_line1="Herengracht 597",
        address_line2="",
        city="Amsterdam",
        region="North Holland",
        postal_code="1017 CE",
        country="Netherlands",
        po_box="",
        phone="",
        contact_email="",
        location="Amsterdam, Netherlands",
        latitude=52.3676,
        longitude=4.9041,
        founded_year=1996,
        short_history="Booking.com started in the Netherlands and became a global online travel platform within Booking Holdings.",
    ),
    CompanyRecord(
        id="company-flutter-entertainment",
        name="Flutter Entertainment",
        description="Global sports betting, gaming, and entertainment group operating consumer brands across regulated markets.",
        website="https://www.flutter.com",
        industry="Gambling and gaming",
        headquarters="New York, NY",
        size="10000+",
        legal_name="Flutter Entertainment plc",
        address_line1="One Madison Avenue",
        address_line2="",
        city="New York",
        region="NY",
        postal_code="10010",
        country="US",
        po_box="",
        phone="",
        contact_email="",
        location="New York, NY, US",
        latitude=40.7411,
        longitude=-73.9872,
        founded_year=2016,
        short_history="Flutter Entertainment was created through mergers of major betting and gaming operators and now runs multiple regulated gambling brands.",
    ),
]


JobFilterMetadata: TypeAlias = dict[str, JobUpdateValue]

_DESCRIPTION_NOTE_FIELD = "description_note"
_JOB_RECORD_FIELD_NAMES = frozenset(field.name for field in fields(JobRecord))


_EXISTING_JOB_FILTER_METADATA: dict[str, JobFilterMetadata] = {
    "job-001": {
        "eligible_countries": ["US"],
        "office_cities": [],
        "visa_sponsorship": True,
        "timezone_overlap_hours": 3,
        "equity_offered": True,
        "languages_required": ["en"],
        "languages_nice_to_have": ["ru"],
        "role_focus": ["backend-engineering", "ai-engineering", "python-backend"],
        "domain_tags": ["recruiting", "ai-tools"],
        "on_call_policy": "business-hours",
        "description_note": "Additional filter context: this is a remote US role with US visa sponsorship possible, English required, Russian helpful, equity eligible compensation, roughly three hours of Asia/Almaty overlap, and business-hours support rather than 24/7 on-call.",
    },
    "job-002": {
        "eligible_countries": ["US"],
        "office_cities": [],
        "visa_sponsorship": True,
        "timezone_overlap_hours": 3,
        "equity_offered": True,
        "languages_required": ["en"],
        "languages_nice_to_have": [],
        "role_focus": ["data-engineering"],
        "domain_tags": ["recruiting", "analytics"],
        "on_call_policy": "none",
        "description_note": "Additional filter context: this is remote within the US, visa sponsorship can be considered, English is required, compensation includes equity, Asia/Almaty overlap is limited to about three hours, and there is no regular on-call rotation.",
    },
    "job-003": {
        "eligible_countries": ["US"],
        "office_cities": ["Austin"],
        "visa_sponsorship": False,
        "timezone_overlap_hours": 2,
        "equity_offered": True,
        "languages_required": ["en"],
        "languages_nice_to_have": [],
        "role_focus": ["product-management", "ai-product"],
        "domain_tags": ["recruiting", "ai-tools"],
        "on_call_policy": "none",
        "relocation_required": True,
        "relocation_countries": ["US"],
        "deal_breaker_tags": ["requires-us-relocation"],
        "description_note": "Additional filter context: this Austin hybrid role requires relocation to the US, does not offer visa sponsorship, works in English, has only about two hours of Asia/Almaty overlap, and should be treated as a US-relocation negative case.",
    },
    "job-004": {
        "eligible_countries": ["Germany", "UK", "Netherlands"],
        "office_cities": ["Berlin"],
        "visa_sponsorship": True,
        "timezone_overlap_hours": 5,
        "equity_offered": True,
        "languages_required": ["en"],
        "languages_nice_to_have": ["de"],
        "role_focus": ["platform-engineering", "infrastructure"],
        "domain_tags": ["cloud", "platform"],
        "on_call_policy": "business-hours",
        "description_note": "Additional filter context: the role is hybrid in Berlin, Germany, offers visa sponsorship, requires English with German nice to have, provides five hours of Asia/Almaty overlap, and keeps support to business hours.",
    },
    "job-005": {
        "eligible_countries": ["Germany"],
        "office_cities": ["Berlin"],
        "visa_sponsorship": True,
        "timezone_overlap_hours": 5,
        "equity_offered": True,
        "languages_required": ["en"],
        "languages_nice_to_have": ["de"],
        "role_focus": ["platform-engineering", "site-reliability"],
        "domain_tags": ["cloud", "platform"],
        "on_call_policy": "24-7",
        "description_note": "Additional filter context: this Berlin role can sponsor a German visa and has good Asia/Almaty overlap, but it explicitly includes a 24/7 incident on-call rotation that preference filters should penalize.",
    },
    "job-006": {
        "eligible_countries": ["Germany", "Netherlands", "UK"],
        "office_cities": [],
        "visa_sponsorship": False,
        "timezone_overlap_hours": 4,
        "equity_offered": True,
        "languages_required": ["en"],
        "languages_nice_to_have": ["de"],
        "role_focus": ["platform-engineering", "developer-experience"],
        "domain_tags": ["developer-platform"],
        "on_call_policy": "business-hours",
        "description_note": "Additional filter context: this remote Europe role accepts Germany, Netherlands, or UK time zones, requires English, has four hours of Asia/Almaty overlap, but does not provide visa sponsorship.",
    },
    "job-007": {
        "eligible_countries": ["US"],
        "office_cities": ["New York"],
        "visa_sponsorship": False,
        "timezone_overlap_hours": 2,
        "equity_offered": True,
        "languages_required": ["en"],
        "languages_nice_to_have": [],
        "role_focus": ["machine-learning", "pure-ml-research"],
        "domain_tags": ["search", "social-media"],
        "on_call_policy": "none",
        "relocation_required": True,
        "relocation_countries": ["US"],
        "deal_breaker_tags": ["requires-us-relocation"],
        "description_note": "Additional filter context: this onsite New York role requires US relocation, has no visa sponsorship for the target profile, has low Asia/Almaty overlap, and leans toward pure ML research rather than backend or data platform work.",
    },
    "job-008": {
        "eligible_countries": ["US"],
        "office_cities": ["New York"],
        "visa_sponsorship": False,
        "timezone_overlap_hours": 2,
        "equity_offered": True,
        "languages_required": ["en"],
        "languages_nice_to_have": [],
        "role_focus": ["data-analysis", "search-relevance"],
        "domain_tags": ["search", "social-media"],
        "on_call_policy": "none",
        "relocation_required": True,
        "relocation_countries": ["US"],
        "deal_breaker_tags": ["requires-us-relocation"],
        "description_note": "Additional filter context: this is onsite in New York, requires relocation to the US, does not sponsor the target visa path, uses English, and is an analyst role rather than senior data engineering.",
    },
    "job-009": {
        "eligible_countries": ["US"],
        "office_cities": [],
        "visa_sponsorship": True,
        "timezone_overlap_hours": 3,
        "equity_offered": True,
        "languages_required": ["en"],
        "languages_nice_to_have": [],
        "role_focus": ["backend-engineering", "python-backend"],
        "domain_tags": ["search", "apis"],
        "on_call_policy": "rotating",
        "description_note": "Additional filter context: this remote US backend role uses Python APIs, can consider visa sponsorship, requires English, includes equity, has about three hours of Asia/Almaty overlap, and has a light rotating support rota.",
    },
    "job-010": {
        "eligible_countries": ["Germany", "Netherlands", "UK"],
        "office_cities": [],
        "visa_sponsorship": False,
        "timezone_overlap_hours": 4,
        "equity_offered": False,
        "languages_required": ["en"],
        "languages_nice_to_have": ["de"],
        "role_focus": ["frontend-only", "frontend-engineering"],
        "domain_tags": ["operations-software"],
        "on_call_policy": "none",
        "description_note": "Additional filter context: this is a remote Europe contract role with no visa sponsorship, English required, German nice to have, enough Asia/Almaty overlap, and intentionally frontend-only work.",
    },
    "job-011": {
        "eligible_countries": ["UK"],
        "office_cities": ["London"],
        "visa_sponsorship": True,
        "timezone_overlap_hours": 4,
        "equity_offered": True,
        "languages_required": ["en"],
        "languages_nice_to_have": [],
        "role_focus": ["ux-research"],
        "domain_tags": ["operations-software"],
        "on_call_policy": "none",
        "description_note": "Additional filter context: this London role offers UK visa sponsorship and four hours of Asia/Almaty overlap, but it is UX research rather than backend, data, platform, or infra engineering.",
    },
    "job-012": {
        "eligible_countries": ["UK"],
        "office_cities": [],
        "visa_sponsorship": True,
        "timezone_overlap_hours": 4,
        "equity_offered": True,
        "languages_required": ["en"],
        "languages_nice_to_have": [],
        "role_focus": ["implementation", "customer-success"],
        "domain_tags": ["operations-software"],
        "on_call_policy": "business-hours",
        "description_note": "Additional filter context: this remote UK role can sponsor a visa and has good Asia/Almaty overlap, but it is implementation consulting rather than the target engineering roles.",
    },
    "job-013": {
        "eligible_countries": ["US"],
        "office_cities": ["San Francisco"],
        "visa_sponsorship": False,
        "timezone_overlap_hours": 2,
        "salary_period": "hour",
        "equity_offered": False,
        "languages_required": ["en"],
        "languages_nice_to_have": [],
        "role_focus": ["internship", "ai-engineering"],
        "domain_tags": ["ai-tools"],
        "on_call_policy": "none",
        "relocation_required": True,
        "relocation_countries": ["US"],
        "deal_breaker_tags": ["requires-us-relocation"],
        "description_note": "Additional filter context: this is a junior internship in San Francisco, paid hourly rather than annual salary, with no visa sponsorship and required US relocation.",
    },
    "job-014": {
        "eligible_countries": ["US"],
        "office_cities": [],
        "visa_sponsorship": False,
        "timezone_overlap_hours": 3,
        "equity_offered": False,
        "languages_required": ["en"],
        "languages_nice_to_have": [],
        "role_focus": ["prompt-evaluation", "quality-operations"],
        "domain_tags": ["ai-tools"],
        "on_call_policy": "none",
        "description_note": "Additional filter context: this remote US contract role has no visa sponsorship, English-only work, no equity, and is evaluation operations rather than backend, data, or platform engineering.",
    },
    "job-015": {
        "eligible_countries": ["US"],
        "office_cities": ["San Francisco"],
        "visa_sponsorship": False,
        "timezone_overlap_hours": 2,
        "equity_offered": True,
        "languages_required": ["en"],
        "languages_nice_to_have": [],
        "role_focus": ["solutions-engineering", "applied-ai"],
        "domain_tags": ["ai-tools", "customer-engineering"],
        "on_call_policy": "business-hours",
        "relocation_required": True,
        "relocation_countries": ["US"],
        "deal_breaker_tags": ["requires-us-relocation"],
        "description_note": "Additional filter context: this San Francisco hybrid job requires US relocation, does not sponsor the target visa path, has low Asia/Almaty overlap, and is solutions engineering rather than the target roles.",
    },
}


MOCK_JOBS: list[JobRecord] = [
    JobRecord(
        id="job-001",
        title="AI Agent Engineer",
        company_id="company-alphabet",
        location="Remote - US",
        work_mode="remote",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=160000, max=210000),
        profession_tags=["ai-engineering", "backend-engineering"],
        skills_tags=["typescript", "python", "mcp", "agents", "valkey", "llm"],
        candidate_qualities=["ownership", "systems-thinking", "clear-writing"],
        summary="Build agent tooling and evaluation loops for internal recruiting workflows.",
        description="You will design and ship agent workflows that help recruiting teams source, screen, and follow up with candidates. The role covers MCP tool integration, prompt and policy design, evaluation harnesses, and production monitoring. You should be comfortable moving from a rough workflow idea to a reliable internal service used by non-engineering teams.",
        posted_at="2026-04-22",
        application_url="https://example.com/jobs/job-001",
    ),
    JobRecord(
        id="job-002",
        title="Recruiting Data Engineer",
        company_id="company-alphabet",
        location="Remote - US",
        work_mode="remote",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=130000, max=170000),
        profession_tags=["data-engineering", "analytics-engineering"],
        skills_tags=["python", "sql", "dbt", "airflow", "valkey"],
        candidate_qualities=["data-quality", "stakeholder-empathy", "pragmatism"],
        summary="Build clean recruiting datasets and operational analytics for agent-assisted workflows.",
        description="Alphabet is hiring a data engineer to own the pipelines that feed recruiting automation products. You will model candidate, job, outreach, and interview data; build quality checks; and partner with product teams to make sure automation decisions are explainable and measurable. This is a hands-on role with room to shape data standards across the company.",
        posted_at="2026-04-21",
        application_url="https://example.com/jobs/job-002",
    ),
    JobRecord(
        id="job-003",
        title="Product Manager, Agent Workflows",
        company_id="company-alphabet",
        location="Austin, TX",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=150000, max=195000),
        profession_tags=["product-management", "ai-product"],
        skills_tags=["roadmapping", "user-research", "experimentation", "analytics"],
        candidate_qualities=["structured-thinking", "customer-focus", "clear-communication"],
        summary="Lead product direction for internal recruiting agents and workflow automation.",
        description="You will define the roadmap for agent-assisted recruiting workflows, working closely with recruiters, engineers, and operations leaders. The work includes discovery, workflow mapping, launch planning, experiment design, and success metrics. A strong candidate can translate ambiguous operational pain into scoped product bets and measurable releases.",
        posted_at="2026-04-19",
        application_url="https://example.com/jobs/job-003",
    ),
    JobRecord(
        id="job-004",
        title="Platform Engineer",
        company_id="company-amazon",
        location="Berlin, Germany",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=95000, max=130000),
        profession_tags=["platform-engineering", "devops"],
        skills_tags=["go", "kubernetes", "terraform", "observability"],
        candidate_qualities=["production-ownership", "collaboration"],
        summary="Maintain platform foundations for data and automation teams.",
        description="Amazon is looking for a platform engineer to improve the infrastructure used by product and data teams. You will work on Kubernetes clusters, service templates, Terraform modules, observability defaults, and incident readiness. The team values practical automation, clear runbooks, and a measured approach to production change.",
        posted_at="2026-04-18",
        application_url="https://example.com/jobs/job-004",
    ),
    JobRecord(
        id="job-005",
        title="Site Reliability Engineer",
        company_id="company-amazon",
        location="Berlin, Germany",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=125000, max=165000),
        profession_tags=["site-reliability", "platform-engineering"],
        skills_tags=["linux", "kubernetes", "prometheus", "incident-response"],
        candidate_qualities=["calm-under-pressure", "ownership", "systems-debugging"],
        summary="Improve reliability practices for a multi-tenant infrastructure product.",
        description="You will help Amazon operate customer-facing infrastructure with better alerting, capacity planning, and incident response. The role includes on-call participation, post-incident reviews, SLO design, and reliability improvements across deployment and runtime systems. You should be able to debug distributed systems and turn repeated failures into durable fixes.",
        posted_at="2026-04-24",
        application_url="https://example.com/jobs/job-005",
    ),
    JobRecord(
        id="job-006",
        title="Developer Experience Engineer",
        company_id="company-amazon",
        location="Remote - Europe",
        work_mode="remote",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=105000, max=145000),
        profession_tags=["developer-experience", "platform-engineering"],
        skills_tags=["go", "python", "ci-cd", "documentation", "internal-tools"],
        candidate_qualities=["empathy", "technical-writing", "bias-for-action"],
        summary="Make internal platform tools easier for engineering teams to adopt and operate.",
        description="This role focuses on the developer-facing layer of Cinder's platform: CLIs, templates, docs, examples, and golden paths. You will interview engineers, remove friction from common workflows, and build tooling that makes the right production practices the easiest path. Success means teams ship services faster without losing operational discipline.",
        posted_at="2026-04-17",
        application_url="https://example.com/jobs/job-006",
    ),
    JobRecord(
        id="job-007",
        title="Machine Learning Engineer",
        company_id="company-meta",
        location="New York, NY",
        work_mode="onsite",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=180000, max=240000),
        profession_tags=["machine-learning", "search-engineering"],
        skills_tags=["python", "pytorch", "rag", "evaluation"],
        candidate_qualities=["research-judgment", "experimentation"],
        summary="Ship retrieval and ranking systems for a search-heavy product.",
        description="Meta Platforms needs an ML engineer to improve retrieval, ranking, and answer quality for a search-heavy product. You will build offline evaluation sets, run ranking experiments, optimize inference paths, and partner with product teams to understand where search quality breaks down for users. The role balances modeling work with practical production engineering.",
        posted_at="2026-04-25",
        application_url="https://example.com/jobs/job-007",
    ),
    JobRecord(
        id="job-008",
        title="Search Relevance Analyst",
        company_id="company-meta",
        location="New York, NY",
        work_mode="onsite",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=95000, max=125000),
        profession_tags=["search-relevance", "data-analysis"],
        skills_tags=["sql", "python", "experimentation", "ranking", "dashboards"],
        candidate_qualities=["curiosity", "attention-to-detail", "user-empathy"],
        summary="Analyze query behavior and help tune relevance for high-value search journeys.",
        description="You will investigate search logs, label result quality, build dashboards, and recommend changes to ranking and retrieval systems. The work sits between data analysis, product insight, and search quality operations. A good fit is comfortable with messy behavioral data and can explain relevance problems in concrete terms.",
        posted_at="2026-04-23",
        application_url="https://example.com/jobs/job-008",
    ),
    JobRecord(
        id="job-009",
        title="Backend Engineer, Retrieval APIs",
        company_id="company-meta",
        location="Remote - US",
        work_mode="remote",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=170000, max=220000),
        profession_tags=["backend-engineering", "search-engineering"],
        skills_tags=["python", "fastapi", "postgres", "vector-search", "distributed-systems"],
        candidate_qualities=["api-design", "reliability-minded", "debugging-depth"],
        summary="Build low-latency APIs for retrieval, ranking, and search experimentation.",
        description="Meta Platforms is hiring a backend engineer to own service boundaries around retrieval and ranking APIs. You will design endpoints, optimize query paths, improve observability, and support experimentation infrastructure used by ML and product teams. Experience with search, vector databases, or high-throughput APIs is useful but not required.",
        posted_at="2026-04-16",
        application_url="https://example.com/jobs/job-009",
    ),
    JobRecord(
        id="job-010",
        title="Frontend Engineer",
        company_id="company-microsoft",
        location="Remote - Europe",
        work_mode="remote",
        employment_type="contract",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=70000, max=100000),
        profession_tags=["frontend-engineering", "product-engineering"],
        skills_tags=["react", "typescript", "design-systems", "accessibility"],
        candidate_qualities=["product-sense", "attention-to-detail"],
        summary="Build polished user flows for a B2B operations dashboard.",
        description="Microsoft builds dense operational interfaces for logistics teams, and this role owns the frontend experience. You will work on React workflows, shared components, accessibility, data-heavy screens, and performance improvements. The best candidates care about small interaction details and know how to make complex software feel predictable for daily users.",
        posted_at="2026-04-20",
        application_url="https://example.com/jobs/job-010",
    ),
    JobRecord(
        id="job-011",
        title="UX Researcher, Operations Software",
        company_id="company-microsoft",
        location="London, UK",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=85000, max=115000),
        profession_tags=["ux-research", "product-design"],
        skills_tags=["interviews", "usability-testing", "journey-mapping", "synthesis"],
        candidate_qualities=["listening", "structured-synthesis", "field-research"],
        summary="Research how dispatch and operations teams use complex workflow software.",
        description="You will plan and run research with dispatchers, operations managers, and implementation teams. The work includes usability studies, workflow observation, customer interviews, and clear synthesis that shapes roadmap decisions. Microsoft needs someone who can understand operational nuance and turn field learning into product direction.",
        posted_at="2026-04-15",
        application_url="https://example.com/jobs/job-011",
    ),
    JobRecord(
        id="job-012",
        title="Implementation Consultant",
        company_id="company-microsoft",
        location="Remote - UK",
        work_mode="remote",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=80000, max=105000),
        profession_tags=["implementation", "customer-success"],
        skills_tags=["workflow-design", "sql", "training", "stakeholder-management"],
        candidate_qualities=["patience", "customer-empathy", "organization"],
        summary="Help new customers configure Microsoft workflow products around real operations needs.",
        description="This role guides customers from signed contract to a live operational rollout. You will map current workflows, configure dashboards, validate data, train users, and surface product gaps to engineering. It is a strong fit for someone who likes customer work but can also reason about systems, data, and process design.",
        posted_at="2026-04-14",
        application_url="https://example.com/jobs/job-012",
    ),
    JobRecord(
        id="job-013",
        title="Applied AI Intern",
        company_id="company-nvidia",
        location="San Francisco, CA",
        work_mode="hybrid",
        employment_type="internship",
        seniority="junior",
        salary_range=SalaryRange(currency="USD", min=35, max=50),
        profession_tags=["ai-engineering", "internship"],
        skills_tags=["python", "agents", "prompting", "evaluation"],
        candidate_qualities=["curiosity", "fast-learning"],
        summary="Prototype internal tools that help recruiters and candidates move faster.",
        description="NVIDIA is hiring an intern to help prototype applied AI tools for recruiting workflows. You will write small Python services, test prompt variants, connect tools, and summarize experiment results for the team. This is a learning-heavy role for someone who has built projects, asks precise questions, and can turn feedback into quick iterations.",
        posted_at="2026-04-24",
        application_url="https://example.com/jobs/job-013",
    ),
    JobRecord(
        id="job-014",
        title="Prompt Evaluation Specialist",
        company_id="company-nvidia",
        location="Remote - US",
        work_mode="remote",
        employment_type="contract",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=65000, max=95000),
        profession_tags=["ai-evaluation", "prompt-engineering"],
        skills_tags=["prompting", "evaluation", "spreadsheets", "quality-review"],
        candidate_qualities=["precision", "taste", "documentation"],
        summary="Design and review evaluation sets for recruiting assistant behavior.",
        description="You will create test cases, review model outputs, document failure modes, and help the team improve assistant prompts. The work requires careful reading, consistent judgment, and the ability to explain why an answer is or is not acceptable in a recruiting context. Experience with LLM evaluation or quality operations is helpful.",
        posted_at="2026-04-13",
        application_url="https://example.com/jobs/job-014",
    ),
    JobRecord(
        id="job-015",
        title="Customer Solutions Engineer",
        company_id="company-nvidia",
        location="San Francisco, CA",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=115000, max=150000),
        profession_tags=["solutions-engineering", "applied-ai"],
        skills_tags=["python", "apis", "customer-discovery", "technical-demos"],
        candidate_qualities=["communication", "adaptability", "technical-judgment"],
        summary="Build customer demos and lightweight integrations for applied AI recruiting tools.",
        description="You will partner with founders and customers to understand recruiting workflows, build demos, wire up APIs, and translate pilot feedback into product requirements. This is a hands-on technical customer role that rewards clear communication, fast prototyping, and good judgment about what should become product versus one-off support.",
        posted_at="2026-04-12",
        application_url="https://example.com/jobs/job-015",
    ),
    JobRecord(
        id="job-016",
        title="Senior Data Engineer, Markets Data",
        company_id="company-jpmorgan-chase",
        location="London, UK",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=120000, max=165000),
        profession_tags=["data-engineering", "capital-markets"],
        skills_tags=["python", "clickhouse", "dlt", "sql", "airflow", "dbt"],
        candidate_qualities=["data-quality", "ownership", "stakeholder-empathy"],
        summary="Build market-data pipelines and analytical datasets for trading and risk teams.",
        description="JPMorgan Chase is hiring a senior data engineer for its London markets technology group. The role is hybrid in London and open to candidates already based in the UK, Germany, Netherlands, or Kazakhstan who can maintain at least four hours of overlap with Asia/Almaty. Visa sponsorship is available for the UK. The team works in English, with Russian or German helpful but not required. Python, ClickHouse, DLT, SQL, Airflow, and dbt experience are strong matches. The domain is capital markets and financial data, includes equity participation in compensation, and does not require 24/7 on-call.",
        posted_at="2026-04-27",
        application_url="https://example.com/jobs/job-016",
        eligible_countries=["UK", "Germany", "Netherlands", "Kazakhstan"],
        office_cities=["London"],
        visa_sponsorship=True,
        timezone_overlap_hours=4,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=["ru", "de"],
        role_focus=["data-engineering"],
        domain_tags=["fintech", "capital-markets", "banking"],
        on_call_policy="business-hours",
    ),
    JobRecord(
        id="job-017",
        title="Backend Engineer (Python), Payments Platform",
        company_id="company-jpmorgan-chase",
        location="London, UK",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=95000, max=130000),
        profession_tags=["backend-engineering", "payments"],
        skills_tags=["python", "fastapi", "postgres", "kafka", "apis"],
        candidate_qualities=["api-design", "reliability-minded", "clear-communication"],
        summary="Build Python services for institutional payment workflows and controls.",
        description="This London-based backend role focuses on Python and FastAPI services used by institutional payment teams. JPMorgan Chase can sponsor a UK work visa for qualified candidates and expects English fluency; Russian or German is a plus for cross-region stakeholders. The role supports candidates in the UK, Germany, Netherlands, or Kazakhstan if they can work with four hours of Asia/Almaty overlap. Compensation is annual base salary with equity eligible awards. The team has business-hours support only, no 24/7 rotation, and the work sits in fintech and banking rather than crypto trading.",
        posted_at="2026-04-26",
        application_url="https://example.com/jobs/job-017",
        eligible_countries=["UK", "Germany", "Netherlands", "Kazakhstan"],
        office_cities=["London"],
        visa_sponsorship=True,
        timezone_overlap_hours=4,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=["ru", "de"],
        role_focus=["backend-engineering", "python-backend"],
        domain_tags=["fintech", "payments", "banking"],
        on_call_policy="business-hours",
    ),
    JobRecord(
        id="job-018",
        title="Platform / Infra Engineer, Developer Cloud",
        company_id="company-jpmorgan-chase",
        location="Remote - UK",
        work_mode="remote",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=110000, max=150000),
        profession_tags=["platform-engineering", "infrastructure"],
        skills_tags=["python", "kubernetes", "terraform", "aws", "observability"],
        candidate_qualities=["systems-thinking", "production-ownership", "pragmatism"],
        summary="Own cloud platform foundations for internal engineering teams.",
        description="This platform role is remote within the UK and may consider candidates from Germany, the Netherlands, or Kazakhstan who can keep at least four hours of overlap with Asia/Almaty. JPMorgan Chase offers visa sponsorship for UK relocation when needed, but relocation is not required for already eligible remote workers. The stack includes Kubernetes, Terraform, AWS, Python automation, and observability. English is required and German or Russian is helpful. There is a rotating daytime support rota, but no 24/7 on-call expectation.",
        posted_at="2026-04-24",
        application_url="https://example.com/jobs/job-018",
        eligible_countries=["UK", "Germany", "Netherlands", "Kazakhstan"],
        office_cities=["London"],
        visa_sponsorship=True,
        timezone_overlap_hours=4,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=["ru", "de"],
        role_focus=["platform-engineering", "infrastructure"],
        domain_tags=["fintech", "developer-platform", "banking"],
        on_call_policy="rotating",
    ),
    JobRecord(
        id="job-019",
        title="Platform Engineer, Industrial Edge",
        company_id="company-siemens",
        location="Berlin, Germany",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=80000, max=115000),
        profession_tags=["platform-engineering", "industrial-iot"],
        skills_tags=["python", "kubernetes", "terraform", "linux", "observability"],
        candidate_qualities=["systems-thinking", "collaboration", "operational-discipline"],
        summary="Run platform foundations for industrial edge and automation products.",
        description="Siemens is hiring a hybrid platform engineer in Berlin for industrial edge products. Visa sponsorship for Germany is available, and the team can work with candidates from Germany, the Netherlands, the UK, or Kazakhstan if they can overlap with Asia/Almaty for at least five hours. English is required and German is a strong plus. The work uses Python automation, Kubernetes, Terraform, Linux, and observability. There is a planned daytime rotation for releases, but no 24/7 on-call.",
        posted_at="2026-04-23",
        application_url="https://example.com/jobs/job-019",
        eligible_countries=["Germany", "Netherlands", "UK", "Kazakhstan"],
        office_cities=["Berlin"],
        visa_sponsorship=True,
        timezone_overlap_hours=5,
        equity_offered=False,
        languages_required=["en"],
        languages_nice_to_have=["de"],
        role_focus=["platform-engineering", "infrastructure"],
        domain_tags=["industrial", "manufacturing", "iot"],
        on_call_policy="business-hours",
    ),
    JobRecord(
        id="job-020",
        title="Backend Engineer (Python), Factory Data APIs",
        company_id="company-siemens",
        location="Berlin, Germany",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=76000, max=106000),
        profession_tags=["backend-engineering", "industrial-data"],
        skills_tags=["python", "fastapi", "postgres", "kafka", "iot"],
        candidate_qualities=["api-design", "customer-focus", "debugging-depth"],
        summary="Build Python APIs for factory telemetry and production planning data.",
        description="This Berlin role builds FastAPI services for factory telemetry, production planning, and equipment data. Siemens can sponsor a German work visa and expects English; German is nice to have. Candidates in Kazakhstan, Germany, the Netherlands, or the UK are acceptable when they can keep five hours of overlap with Asia/Almaty. The role is full-time, not contract, and compensation is annual salary with no equity component. Support is during business hours only.",
        posted_at="2026-04-22",
        application_url="https://example.com/jobs/job-020",
        eligible_countries=["Germany", "Netherlands", "UK", "Kazakhstan"],
        office_cities=["Berlin"],
        visa_sponsorship=True,
        timezone_overlap_hours=5,
        equity_offered=False,
        languages_required=["en"],
        languages_nice_to_have=["de"],
        role_focus=["backend-engineering", "python-backend"],
        domain_tags=["industrial", "manufacturing", "iot"],
        on_call_policy="business-hours",
    ),
    JobRecord(
        id="job-021",
        title="Senior Data Engineer, Mobility Analytics",
        company_id="company-siemens",
        location="Munich, Germany",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=82000, max=118000),
        profession_tags=["data-engineering", "analytics-engineering"],
        skills_tags=["python", "sql", "dbt", "spark", "airflow"],
        candidate_qualities=["data-quality", "structured-thinking", "stakeholder-empathy"],
        summary="Model mobility and infrastructure data for operational analytics teams.",
        description="Siemens is hiring a senior data engineer in Munich, Germany. Visa sponsorship is available and the team works primarily in English, with German nice to have. This is intentionally not a Berlin role, so city-based filters should treat it differently even though the country is Germany. The stack includes Python, SQL, dbt, Spark, and Airflow. The job has at least five hours of overlap with Asia/Almaty and does not include a 24/7 on-call rotation.",
        posted_at="2026-04-21",
        application_url="https://example.com/jobs/job-021",
        eligible_countries=["Germany", "Netherlands", "UK", "Kazakhstan"],
        office_cities=["Munich"],
        visa_sponsorship=True,
        timezone_overlap_hours=5,
        equity_offered=False,
        languages_required=["en"],
        languages_nice_to_have=["de"],
        role_focus=["data-engineering"],
        domain_tags=["industrial", "mobility", "analytics"],
        on_call_policy="none",
    ),
    JobRecord(
        id="job-022",
        title="Senior Data Engineer, Capital Markets",
        company_id="company-ing",
        location="Amsterdam, Netherlands",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=95000, max=132000),
        profession_tags=["data-engineering", "capital-markets"],
        skills_tags=["python", "clickhouse", "sql", "dbt", "dlt", "airflow"],
        candidate_qualities=["ownership", "data-quality", "risk-awareness"],
        summary="Build analytical data products for markets, treasury, and risk workflows.",
        description="ING is looking for a senior data engineer in Amsterdam for capital markets and treasury data products. Visa sponsorship is available for the Netherlands. English is required, while Russian or German is useful for some distributed stakeholders. The stack includes Python, ClickHouse, DLT, SQL, dbt, and Airflow, and the position has five hours of Asia/Almaty overlap. The team has no 24/7 on-call rotation and this is a full-time employee role, not B2B contract.",
        posted_at="2026-04-27",
        application_url="https://example.com/jobs/job-022",
        eligible_countries=["Netherlands", "Germany", "UK", "Kazakhstan"],
        office_cities=["Amsterdam"],
        visa_sponsorship=True,
        timezone_overlap_hours=5,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=["ru", "de"],
        role_focus=["data-engineering"],
        domain_tags=["fintech", "capital-markets", "banking"],
        on_call_policy="none",
    ),
    JobRecord(
        id="job-023",
        title="Backend Engineer (Python), Open Banking",
        company_id="company-ing",
        location="Amsterdam, Netherlands",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=86000, max=118000),
        profession_tags=["backend-engineering", "open-banking"],
        skills_tags=["python", "fastapi", "postgres", "oauth", "apis"],
        candidate_qualities=["api-design", "security-minded", "clear-writing"],
        summary="Build regulated API services for open-banking integrations.",
        description="This ING role is a Python backend job in Amsterdam working on open-banking APIs with FastAPI, Postgres, OAuth, and service observability. Visa sponsorship is available in the Netherlands, English is required, and German or Russian is a nice-to-have. The role supports candidates able to work with five hours of Asia/Almaty overlap. It is full-time, has equity eligible compensation, and avoids 24/7 on-call.",
        posted_at="2026-04-25",
        application_url="https://example.com/jobs/job-023",
        eligible_countries=["Netherlands", "Germany", "UK", "Kazakhstan"],
        office_cities=["Amsterdam"],
        visa_sponsorship=True,
        timezone_overlap_hours=5,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=["ru", "de"],
        role_focus=["backend-engineering", "python-backend"],
        domain_tags=["fintech", "open-banking", "banking"],
        on_call_policy="business-hours",
    ),
    JobRecord(
        id="job-024",
        title="Java Backend Engineer, Core Banking",
        company_id="company-ing",
        location="Amsterdam, Netherlands",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=90000, max=122000),
        profession_tags=["backend-engineering", "core-banking"],
        skills_tags=["java", "spring", "oracle", "kafka", "microservices"],
        candidate_qualities=["maintenance-mindset", "risk-awareness", "documentation"],
        summary="Maintain Java and Spring services in core banking workflows.",
        description="ING can sponsor a Netherlands visa for this Amsterdam role, and it has good Asia/Almaty overlap, but the backend stack is deliberately Java and Spring heavy with Oracle databases. English is required and Dutch is helpful. The role is useful as a negative test case for filters that avoid Java-heavy backend work even though the company, country, seniority, and compensation might otherwise look acceptable.",
        posted_at="2026-04-20",
        application_url="https://example.com/jobs/job-024",
        eligible_countries=["Netherlands", "Germany", "UK", "Kazakhstan"],
        office_cities=["Amsterdam"],
        visa_sponsorship=True,
        timezone_overlap_hours=5,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=["de"],
        role_focus=["backend-engineering", "java-backend"],
        domain_tags=["fintech", "banking"],
        on_call_policy="business-hours",
    ),
    JobRecord(
        id="job-025",
        title="Senior Data Engineer, Travel Marketplace",
        company_id="company-booking",
        location="Amsterdam, Netherlands",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=100000, max=140000),
        profession_tags=["data-engineering", "marketplace"],
        skills_tags=["python", "spark", "sql", "airflow", "experimentation"],
        candidate_qualities=["data-quality", "product-sense", "experimentation"],
        summary="Build marketplace data products for travel search and partner analytics.",
        description="Booking.com is hiring a senior data engineer in Amsterdam for travel marketplace analytics. Visa sponsorship is available in the Netherlands and English is required; German or Russian is a plus. The team works with Python, Spark, SQL, Airflow, and experimentation data, has five hours of overlap with Asia/Almaty, and does not require 24/7 on-call. This is not fintech, but it should pass many geo, seniority, language, and compensation filters.",
        posted_at="2026-04-24",
        application_url="https://example.com/jobs/job-025",
        eligible_countries=["Netherlands", "Germany", "UK", "Kazakhstan"],
        office_cities=["Amsterdam"],
        visa_sponsorship=True,
        timezone_overlap_hours=5,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=["ru", "de"],
        role_focus=["data-engineering"],
        domain_tags=["travel", "marketplace", "analytics"],
        on_call_policy="none",
    ),
    JobRecord(
        id="job-026",
        title="Frontend-only Engineer, Partner Portal",
        company_id="company-booking",
        location="Amsterdam, Netherlands",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=78000, max=104000),
        profession_tags=["frontend-engineering", "product-engineering"],
        skills_tags=["react", "typescript", "css", "design-systems"],
        candidate_qualities=["product-sense", "attention-to-detail", "accessibility"],
        summary="Build partner-facing web workflows for property managers.",
        description="This Booking.com role is intentionally frontend-only: React, TypeScript, CSS, accessibility, and design systems are the core of the job. Visa sponsorship is available in the Netherlands, English is required, and the Amsterdam location has good Asia/Almaty overlap. It is a useful avoid-role fixture because many hard geo and compensation filters pass, but the role is not backend, data, platform, or infra.",
        posted_at="2026-04-19",
        application_url="https://example.com/jobs/job-026",
        eligible_countries=["Netherlands", "Germany", "UK", "Kazakhstan"],
        office_cities=["Amsterdam"],
        visa_sponsorship=True,
        timezone_overlap_hours=5,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=["de"],
        role_focus=["frontend-only", "frontend-engineering"],
        domain_tags=["travel", "marketplace"],
        on_call_policy="none",
    ),
    JobRecord(
        id="job-027",
        title="Backend Engineer (Python), Experimentation",
        company_id="company-booking",
        location="Remote - Europe",
        work_mode="remote",
        employment_type="contract",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=90000, max=115000),
        profession_tags=["backend-engineering", "experimentation"],
        skills_tags=["python", "fastapi", "postgres", "experimentation", "apis"],
        candidate_qualities=["api-design", "product-sense", "pragmatism"],
        summary="Build Python services for experimentation workflows in travel marketplace teams.",
        description="This is a remote Europe B2B contract role with Booking.com. It uses Python, FastAPI, Postgres, and experimentation services, and it has four hours of overlap with Asia/Almaty. English is required. The role is useful for testing contract rejection: it has good skills, remote-friendly geography, and sufficient pay, but it is explicitly contractor/B2B and does not include visa sponsorship.",
        posted_at="2026-04-18",
        application_url="https://example.com/jobs/job-027",
        eligible_countries=["Germany", "Netherlands", "UK"],
        office_cities=["Amsterdam"],
        visa_sponsorship=False,
        timezone_overlap_hours=4,
        equity_offered=False,
        languages_required=["en"],
        languages_nice_to_have=["de"],
        role_focus=["backend-engineering", "python-backend"],
        domain_tags=["travel", "marketplace", "experimentation"],
        on_call_policy="business-hours",
    ),
    JobRecord(
        id="job-028",
        title="Data Engineer, Gaming Risk",
        company_id="company-flutter-entertainment",
        location="London, UK",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=85000, max=115000),
        profession_tags=["data-engineering", "risk-analytics"],
        skills_tags=["python", "sql", "airflow", "dbt", "fraud-detection"],
        candidate_qualities=["risk-awareness", "data-quality", "attention-to-detail"],
        summary="Build data pipelines for gaming risk and safer gambling analytics.",
        description="Flutter Entertainment is hiring in London for gaming risk data. The role can sponsor a UK visa and has four hours of Asia/Almaty overlap, English is required, and Python plus SQL are central. It is deliberately tagged as gambling and gaming so deal-breaker filters should reject it even though seniority, salary, country, and sponsorship may pass.",
        posted_at="2026-04-17",
        application_url="https://example.com/jobs/job-028",
        eligible_countries=["UK", "Germany", "Netherlands", "Kazakhstan"],
        office_cities=["London"],
        visa_sponsorship=True,
        timezone_overlap_hours=4,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=[],
        role_focus=["data-engineering"],
        domain_tags=["gambling", "gaming", "risk-analytics"],
        on_call_policy="business-hours",
        deal_breaker_tags=["gambling"],
    ),
    JobRecord(
        id="job-029",
        title="Backend Engineer (Python), Betting Platform",
        company_id="company-flutter-entertainment",
        location="Leeds, UK",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=90000, max=125000),
        profession_tags=["backend-engineering", "gaming-platform"],
        skills_tags=["python", "fastapi", "postgres", "kafka", "event-driven"],
        candidate_qualities=["api-design", "production-ownership", "debugging-depth"],
        summary="Build event-driven Python services for regulated betting products.",
        description="This senior backend role at Flutter Entertainment uses Python, FastAPI, Kafka, and Postgres for regulated betting products. Visa sponsorship may be available in the UK and the role overlaps Asia/Almaty for four hours. The description clearly names betting, gambling, and gaming so a deal-breaker parser should auto-reject it despite a strong Python backend match.",
        posted_at="2026-04-16",
        application_url="https://example.com/jobs/job-029",
        eligible_countries=["UK", "Germany", "Netherlands", "Kazakhstan"],
        office_cities=["Leeds"],
        visa_sponsorship=True,
        timezone_overlap_hours=4,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=[],
        role_focus=["backend-engineering", "python-backend"],
        domain_tags=["gambling", "gaming", "betting"],
        on_call_policy="rotating",
        deal_breaker_tags=["gambling"],
    ),
    JobRecord(
        id="job-030",
        title="Platform / Infra Engineer, Gaming Operations",
        company_id="company-flutter-entertainment",
        location="Remote - UK",
        work_mode="remote",
        employment_type="full-time",
        seniority="staff",
        salary_range=SalaryRange(currency="USD", min=115000, max=155000),
        profession_tags=["platform-engineering", "infrastructure"],
        skills_tags=["kubernetes", "terraform", "aws", "prometheus", "incident-response"],
        candidate_qualities=["production-ownership", "systems-debugging", "calm-under-pressure"],
        summary="Operate infrastructure for high-traffic gaming and betting platforms.",
        description="Flutter Entertainment is hiring a staff platform engineer for remote UK infrastructure work. The role has visa support and enough Asia/Almaty overlap, but it sits in gambling and betting, and it includes a 24/7 on-call rotation for major incidents. This listing should be rejected by deal-breaker filters and by preferences that avoid 24/7 on-call.",
        posted_at="2026-04-15",
        application_url="https://example.com/jobs/job-030",
        eligible_countries=["UK"],
        office_cities=["London", "Leeds"],
        visa_sponsorship=True,
        timezone_overlap_hours=4,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=[],
        role_focus=["platform-engineering", "infrastructure"],
        domain_tags=["gambling", "gaming", "betting"],
        on_call_policy="24-7",
        deal_breaker_tags=["gambling"],
    ),
    JobRecord(
        id="job-031",
        title="Staff Data Platform Engineer",
        company_id="company-alphabet",
        location="Remote - Europe",
        work_mode="remote",
        employment_type="full-time",
        seniority="staff",
        salary_range=SalaryRange(currency="USD", min=150000, max=205000),
        profession_tags=["platform-engineering", "data-engineering"],
        skills_tags=["python", "kubernetes", "beam", "bigquery", "terraform", "observability"],
        candidate_qualities=["systems-thinking", "production-ownership", "clear-writing"],
        summary="Build shared data platform primitives for analytics and internal automation teams.",
        description="Alphabet is hiring a staff data platform engineer for remote Europe work. The role accepts candidates in Germany, the Netherlands, the UK, or Kazakhstan when they can keep at least four hours of overlap with Asia/Almaty. Visa sponsorship can be considered for Germany or the UK. English is required, German or Russian is useful, and the stack includes Python, Kubernetes, Beam, BigQuery, Terraform, and observability. The role is full-time with equity and has a daytime support rota, not 24/7 on-call.",
        posted_at="2026-04-28",
        application_url="https://example.com/jobs/job-031",
        eligible_countries=["Germany", "Netherlands", "UK", "Kazakhstan"],
        office_cities=["London", "Berlin", "Amsterdam"],
        visa_sponsorship=True,
        timezone_overlap_hours=4,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=["ru", "de"],
        role_focus=["platform-engineering", "data-engineering"],
        domain_tags=["developer-platform", "analytics", "ai-tools"],
        on_call_policy="rotating",
    ),
    JobRecord(
        id="job-032",
        title="Data Engineer, Logistics Forecasting",
        company_id="company-amazon",
        location="Berlin, Germany",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=90000, max=125000),
        profession_tags=["data-engineering", "logistics"],
        skills_tags=["python", "sql", "spark", "airflow", "forecasting"],
        candidate_qualities=["data-quality", "pragmatism", "stakeholder-empathy"],
        summary="Build forecasting datasets for logistics planning and marketplace operations.",
        description="Amazon is hiring a mid-level data engineer in Berlin for logistics forecasting. Visa sponsorship for Germany is available, English is required, and German is nice to have. The team can work with candidates from Germany, the Netherlands, the UK, or Kazakhstan if they maintain five hours of overlap with Asia/Almaty. The stack is Python, SQL, Spark, and Airflow. This is a full-time employee role with equity eligible compensation and business-hours support only.",
        posted_at="2026-04-27",
        application_url="https://example.com/jobs/job-032",
        eligible_countries=["Germany", "Netherlands", "UK", "Kazakhstan"],
        office_cities=["Berlin"],
        visa_sponsorship=True,
        timezone_overlap_hours=5,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=["de"],
        role_focus=["data-engineering"],
        domain_tags=["logistics", "marketplace", "forecasting"],
        on_call_policy="business-hours",
    ),
    JobRecord(
        id="job-033",
        title="Backend Engineer, Ads Measurement APIs",
        company_id="company-meta",
        location="London, UK",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=135000, max=180000),
        profession_tags=["backend-engineering", "ads-measurement"],
        skills_tags=["python", "graphql", "postgres", "data-modeling", "privacy"],
        candidate_qualities=["api-design", "privacy-awareness", "debugging-depth"],
        summary="Build privacy-aware backend APIs for ads measurement workflows.",
        description="Meta Platforms is hiring a senior backend engineer in London for ads measurement APIs. The role is Python-heavy, with GraphQL, Postgres, privacy controls, and data modeling. UK visa sponsorship is available, English is required, and Russian is a nice-to-have for some distributed team work. Candidates should be able to overlap with Asia/Almaty for at least four hours. The job includes equity and a light business-hours support model, not 24/7 on-call.",
        posted_at="2026-04-26",
        application_url="https://example.com/jobs/job-033",
        eligible_countries=["UK", "Germany", "Netherlands", "Kazakhstan"],
        office_cities=["London"],
        visa_sponsorship=True,
        timezone_overlap_hours=4,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=["ru"],
        role_focus=["backend-engineering", "python-backend"],
        domain_tags=["advertising", "privacy", "analytics"],
        on_call_policy="business-hours",
    ),
    JobRecord(
        id="job-034",
        title="Senior Analytics Engineer, Supply Chain",
        company_id="company-microsoft",
        location="Remote - UK",
        work_mode="remote",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=105000, max=145000),
        profession_tags=["analytics-engineering", "data-engineering"],
        skills_tags=["python", "sql", "dbt", "power-bi", "data-contracts"],
        candidate_qualities=["structured-thinking", "clear-writing", "stakeholder-empathy"],
        summary="Own modeled datasets and metrics for enterprise supply-chain products.",
        description="Microsoft is hiring a remote UK senior analytics engineer for supply-chain product data. UK visa sponsorship is available for strong candidates, English is required, and German is useful but optional. The role has four hours of Asia/Almaty overlap and uses Python, SQL, dbt, Power BI, and data contracts. It is full-time with equity eligible compensation and no 24/7 on-call rotation.",
        posted_at="2026-04-25",
        application_url="https://example.com/jobs/job-034",
        eligible_countries=["UK", "Germany", "Netherlands", "Kazakhstan"],
        office_cities=["London"],
        visa_sponsorship=True,
        timezone_overlap_hours=4,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=["de"],
        role_focus=["data-engineering", "analytics-engineering"],
        domain_tags=["supply-chain", "enterprise-software", "analytics"],
        on_call_policy="none",
    ),
    JobRecord(
        id="job-035",
        title="Infrastructure Engineer, GPU Fleet",
        company_id="company-nvidia",
        location="Berlin, Germany",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="staff",
        salary_range=SalaryRange(currency="USD", min=135000, max=185000),
        profession_tags=["infrastructure", "platform-engineering"],
        skills_tags=["kubernetes", "linux", "terraform", "gpu", "prometheus", "python"],
        candidate_qualities=["systems-debugging", "production-ownership", "calm-under-pressure"],
        summary="Operate platform infrastructure for GPU-backed engineering and simulation workloads.",
        description="NVIDIA is hiring a staff infrastructure engineer in Berlin to work on GPU fleet reliability and platform automation. Visa sponsorship is available for Germany, English is required, and German is nice to have. The team works with Kubernetes, Linux, Terraform, Prometheus, Python automation, and GPU scheduling, with five hours of Asia/Almaty overlap. There is a rotating incident support model but no permanent 24/7 on-call rotation.",
        posted_at="2026-04-24",
        application_url="https://example.com/jobs/job-035",
        eligible_countries=["Germany", "Netherlands", "UK", "Kazakhstan"],
        office_cities=["Berlin"],
        visa_sponsorship=True,
        timezone_overlap_hours=5,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=["de"],
        role_focus=["platform-engineering", "infrastructure"],
        domain_tags=["semiconductors", "gpu", "developer-platform"],
        on_call_policy="rotating",
    ),
    JobRecord(
        id="job-036",
        title="Senior Data Engineer, Compliance Reporting",
        company_id="company-jpmorgan-chase",
        location="Remote - UK",
        work_mode="remote",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=105000, max=145000),
        profession_tags=["data-engineering", "compliance"],
        skills_tags=["python", "sql", "dbt", "airflow", "data-lineage"],
        candidate_qualities=["risk-awareness", "data-quality", "clear-writing"],
        summary="Build regulated reporting pipelines for compliance and risk stakeholders.",
        description="JPMorgan Chase is hiring a remote UK senior data engineer for compliance reporting. The role can sponsor a UK visa, requires English, and values Russian or German for cross-region collaboration. Candidates in the UK, Germany, Netherlands, or Kazakhstan are acceptable with four hours of Asia/Almaty overlap. The stack includes Python, SQL, dbt, Airflow, and data lineage tooling. This is fintech and banking work, full-time, equity eligible, and has no 24/7 on-call.",
        posted_at="2026-04-23",
        application_url="https://example.com/jobs/job-036",
        eligible_countries=["UK", "Germany", "Netherlands", "Kazakhstan"],
        office_cities=["London"],
        visa_sponsorship=True,
        timezone_overlap_hours=4,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=["ru", "de"],
        role_focus=["data-engineering"],
        domain_tags=["fintech", "banking", "compliance"],
        on_call_policy="none",
    ),
    JobRecord(
        id="job-037",
        title="Java / .NET Backend Engineer, Rail Systems",
        company_id="company-siemens",
        location="Berlin, Germany",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=83000, max=116000),
        profession_tags=["backend-engineering", "rail-systems"],
        skills_tags=["java", "csharp", "dotnet", "spring", "oracle"],
        candidate_qualities=["maintenance-mindset", "documentation", "operational-discipline"],
        summary="Maintain Java and .NET backend systems for rail infrastructure products.",
        description="Siemens is hiring a senior backend engineer in Berlin for rail systems. The role offers German visa sponsorship, requires English, and German is helpful. It has five hours of Asia/Almaty overlap and a strong industrial domain, but the stack is deliberately Java and .NET heavy with Spring, C#, and Oracle. This listing is intended as a negative case for filters that avoid Java or .NET-heavy backend work.",
        posted_at="2026-04-22",
        application_url="https://example.com/jobs/job-037",
        eligible_countries=["Germany", "Netherlands", "UK", "Kazakhstan"],
        office_cities=["Berlin"],
        visa_sponsorship=True,
        timezone_overlap_hours=5,
        equity_offered=False,
        languages_required=["en"],
        languages_nice_to_have=["de"],
        role_focus=["backend-engineering", "java-backend", "dotnet-backend"],
        domain_tags=["industrial", "mobility", "rail"],
        on_call_policy="business-hours",
    ),
    JobRecord(
        id="job-038",
        title="Platform Engineer, Payments Observability",
        company_id="company-ing",
        location="Amsterdam, Netherlands",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="staff",
        salary_range=SalaryRange(currency="USD", min=105000, max=145000),
        profession_tags=["platform-engineering", "observability"],
        skills_tags=["python", "kubernetes", "terraform", "prometheus", "opentelemetry"],
        candidate_qualities=["systems-thinking", "reliability-minded", "risk-awareness"],
        summary="Improve observability and platform reliability for regulated payment services.",
        description="ING is hiring a staff platform engineer in Amsterdam for payments observability. Visa sponsorship is available for the Netherlands, English is required, and German or Russian is helpful. The role has five hours of Asia/Almaty overlap and uses Python, Kubernetes, Terraform, Prometheus, and OpenTelemetry. It is fintech and banking work with equity eligible compensation and a rotating daytime support rota, not 24/7 on-call.",
        posted_at="2026-04-21",
        application_url="https://example.com/jobs/job-038",
        eligible_countries=["Netherlands", "Germany", "UK", "Kazakhstan"],
        office_cities=["Amsterdam"],
        visa_sponsorship=True,
        timezone_overlap_hours=5,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=["ru", "de"],
        role_focus=["platform-engineering", "infrastructure"],
        domain_tags=["fintech", "payments", "banking"],
        on_call_policy="rotating",
    ),
    JobRecord(
        id="job-039",
        title="Data Engineer, Partner Risk",
        company_id="company-booking",
        location="London, UK",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=82000, max=112000),
        profession_tags=["data-engineering", "risk-analytics"],
        skills_tags=["python", "sql", "airflow", "dbt", "fraud-detection"],
        candidate_qualities=["data-quality", "risk-awareness", "product-sense"],
        summary="Build partner risk and fraud datasets for travel marketplace operations.",
        description="Booking.com is hiring a London-based data engineer for partner risk analytics. UK visa sponsorship is available, English is required, and German or Russian is useful. The job has four hours of Asia/Almaty overlap, uses Python, SQL, Airflow, dbt, and fraud-detection data, and is a full-time employee role with equity eligible compensation. It is travel marketplace risk work, not gambling, adult, crypto trading, or 24/7 on-call.",
        posted_at="2026-04-20",
        application_url="https://example.com/jobs/job-039",
        eligible_countries=["UK", "Germany", "Netherlands", "Kazakhstan"],
        office_cities=["London"],
        visa_sponsorship=True,
        timezone_overlap_hours=4,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=["ru", "de"],
        role_focus=["data-engineering"],
        domain_tags=["travel", "marketplace", "risk-analytics"],
        on_call_policy="none",
    ),
    JobRecord(
        id="job-040",
        title="Backend Engineer, Responsible Gaming",
        company_id="company-flutter-entertainment",
        location="Amsterdam, Netherlands",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=86000, max=118000),
        profession_tags=["backend-engineering", "responsible-gaming"],
        skills_tags=["python", "fastapi", "postgres", "kafka", "risk-rules"],
        candidate_qualities=["api-design", "risk-awareness", "clear-writing"],
        summary="Build backend services for responsible gaming controls and customer protection.",
        description="Flutter Entertainment is hiring a backend engineer in Amsterdam for responsible gaming controls. The role uses Python, FastAPI, Postgres, Kafka, and risk rules, offers Netherlands visa sponsorship, requires English, and has five hours of Asia/Almaty overlap. It is a full-time employee role with equity, but the company and product domain are gambling and gaming, so deal-breaker filters should reject it even though the backend stack and geography may look attractive.",
        posted_at="2026-04-19",
        application_url="https://example.com/jobs/job-040",
        eligible_countries=["Netherlands", "Germany", "UK", "Kazakhstan"],
        office_cities=["Amsterdam"],
        visa_sponsorship=True,
        timezone_overlap_hours=5,
        equity_offered=True,
        languages_required=["en"],
        languages_nice_to_have=[],
        role_focus=["backend-engineering", "python-backend"],
        domain_tags=["gambling", "gaming", "risk-analytics"],
        on_call_policy="business-hours",
        deal_breaker_tags=["gambling"],
    ),
]


for job in MOCK_JOBS:
    metadata = _EXISTING_JOB_FILTER_METADATA.get(job.id)
    if not metadata:
        continue
    description_note = str(metadata[_DESCRIPTION_NOTE_FIELD])
    for field_name, value in metadata.items():
        if field_name == _DESCRIPTION_NOTE_FIELD:
            continue
        if field_name in _JOB_RECORD_FIELD_NAMES:
            setattr(job, field_name, value)
            continue
        raise ValueError(f"Unknown job metadata field: {field_name}")
    job.description = f"{job.description} {description_note}"
