from __future__ import annotations

from app.models import CompanyRecord, JobRecord, SalaryRange


MOCK_COMPANIES: list[CompanyRecord] = [
    CompanyRecord(
        id="company-alphabet",
        name="Alphabet",
        description="Global technology company with products spanning search, cloud, developer tools, and AI.",
        website="https://abc.xyz",
        industry="Internet services and software",
        headquarters="Mountain View, CA",
        size="10000+",
        legal_name="Alphabet Inc.",
        address_line1="1600 Amphitheatre Parkway",
        address_line2="",
        city="Mountain View",
        region="CA",
        postal_code="94043",
        country="US",
        po_box="",
        phone="",
        contact_email="",
        location="Mountain View, CA, US",
        latitude=37.422,
        longitude=-122.0841,
        founded_year=2015,
        short_history="Alphabet was created in 2015 as the parent company of Google and its broader portfolio of technology businesses.",
    ),
    CompanyRecord(
        id="company-amazon",
        name="Amazon",
        description="Global technology company operating in e-commerce, cloud computing, devices, and digital services.",
        website="https://www.amazon.com",
        industry="E-commerce and cloud computing",
        headquarters="Seattle, WA",
        size="10000+",
        legal_name="Amazon.com, Inc.",
        address_line1="410 Terry Ave N",
        address_line2="",
        city="Seattle",
        region="WA",
        postal_code="98109",
        country="US",
        po_box="",
        phone="",
        contact_email="",
        location="Seattle, WA, US",
        latitude=47.6225,
        longitude=-122.3365,
        founded_year=1994,
        short_history="Amazon started as an online bookstore and expanded into a broad technology platform with AWS and large-scale consumer services.",
    ),
    CompanyRecord(
        id="company-meta",
        name="Meta Platforms",
        description="Technology company focused on social platforms, advertising, developer ecosystems, and AI.",
        website="https://about.meta.com",
        industry="Social media and advertising technology",
        headquarters="Menlo Park, CA",
        size="10000+",
        legal_name="Meta Platforms, Inc.",
        address_line1="1 Meta Way",
        address_line2="",
        city="Menlo Park",
        region="CA",
        postal_code="94025",
        country="US",
        po_box="",
        phone="",
        contact_email="",
        location="Menlo Park, CA, US",
        latitude=37.453,
        longitude=-122.1817,
        founded_year=2004,
        short_history="Meta began as Facebook and later rebranded to reflect its broader product portfolio beyond the flagship social network.",
    ),
    CompanyRecord(
        id="company-microsoft",
        name="Microsoft",
        description="Global software and cloud company spanning productivity products, developer platforms, AI, and enterprise infrastructure.",
        website="https://www.microsoft.com",
        industry="Software and cloud computing",
        headquarters="Redmond, WA",
        size="10000+",
        legal_name="Microsoft Corporation",
        address_line1="One Microsoft Way",
        address_line2="",
        city="Redmond",
        region="WA",
        postal_code="98052",
        country="US",
        po_box="",
        phone="",
        contact_email="",
        location="Redmond, WA, US",
        latitude=47.6396,
        longitude=-122.128,
        founded_year=1975,
        short_history="Microsoft grew from a PC software company into a major cloud, enterprise, productivity, and AI platform provider.",
    ),
    CompanyRecord(
        id="company-nvidia",
        name="NVIDIA",
        description="Technology company known for graphics, accelerated computing, AI hardware, and related software platforms.",
        website="https://www.nvidia.com",
        industry="Semiconductors and AI computing",
        headquarters="Santa Clara, CA",
        size="10000+",
        legal_name="NVIDIA Corporation",
        address_line1="2788 San Tomas Expressway",
        address_line2="",
        city="Santa Clara",
        region="CA",
        postal_code="95051",
        country="US",
        po_box="",
        phone="",
        contact_email="",
        location="Santa Clara, CA, US",
        latitude=37.3875,
        longitude=-121.9637,
        founded_year=1993,
        short_history="NVIDIA started in graphics processing and expanded into accelerated computing infrastructure for AI and data-intensive workloads.",
    ),
]


MOCK_JOBS: list[JobRecord] = [
    JobRecord(
        id="job-001",
        title="AI Agent Engineer",
        company_id="company-alphabet",
        location="Remote - US",
        work_mode="remote",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=160000, max=210000),
        profession_tags=["ai-engineering", "backend-engineering"],
        skills_tags=["typescript", "python", "mcp", "agents", "valkey", "llm"],
        candidate_qualities=["ownership", "systems-thinking", "clear-writing"],
        summary="Build agent tooling and evaluation loops for internal recruiting workflows.",
        description="You will design and ship agent workflows that help recruiting teams source, screen, and follow up with candidates. The role covers MCP tool integration, prompt and policy design, evaluation harnesses, and production monitoring. You should be comfortable moving from a rough workflow idea to a reliable internal service used by non-engineering teams.",
        posted_at="2026-04-22",
        application_url="https://example.com/jobs/job-001",
    ),
    JobRecord(
        id="job-002",
        title="Recruiting Data Engineer",
        company_id="company-alphabet",
        location="Remote - US",
        work_mode="remote",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=130000, max=170000),
        profession_tags=["data-engineering", "analytics-engineering"],
        skills_tags=["python", "sql", "dbt", "airflow", "valkey"],
        candidate_qualities=["data-quality", "stakeholder-empathy", "pragmatism"],
        summary="Build clean recruiting datasets and operational analytics for agent-assisted workflows.",
        description="Alphabet is hiring a data engineer to own the pipelines that feed recruiting automation products. You will model candidate, job, outreach, and interview data; build quality checks; and partner with product teams to make sure automation decisions are explainable and measurable. This is a hands-on role with room to shape data standards across the company.",
        posted_at="2026-04-21",
        application_url="https://example.com/jobs/job-002",
    ),
    JobRecord(
        id="job-003",
        title="Product Manager, Agent Workflows",
        company_id="company-alphabet",
        location="Austin, TX",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=150000, max=195000),
        profession_tags=["product-management", "ai-product"],
        skills_tags=["roadmapping", "user-research", "experimentation", "analytics"],
        candidate_qualities=["structured-thinking", "customer-focus", "clear-communication"],
        summary="Lead product direction for internal recruiting agents and workflow automation.",
        description="You will define the roadmap for agent-assisted recruiting workflows, working closely with recruiters, engineers, and operations leaders. The work includes discovery, workflow mapping, launch planning, experiment design, and success metrics. A strong candidate can translate ambiguous operational pain into scoped product bets and measurable releases.",
        posted_at="2026-04-19",
        application_url="https://example.com/jobs/job-003",
    ),
    JobRecord(
        id="job-004",
        title="Platform Engineer",
        company_id="company-amazon",
        location="Berlin, Germany",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=95000, max=130000),
        profession_tags=["platform-engineering", "devops"],
        skills_tags=["go", "kubernetes", "terraform", "observability"],
        candidate_qualities=["production-ownership", "collaboration"],
        summary="Maintain platform foundations for data and automation teams.",
        description="Amazon is looking for a platform engineer to improve the infrastructure used by product and data teams. You will work on Kubernetes clusters, service templates, Terraform modules, observability defaults, and incident readiness. The team values practical automation, clear runbooks, and a measured approach to production change.",
        posted_at="2026-04-18",
        application_url="https://example.com/jobs/job-004",
    ),
    JobRecord(
        id="job-005",
        title="Site Reliability Engineer",
        company_id="company-amazon",
        location="Berlin, Germany",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=125000, max=165000),
        profession_tags=["site-reliability", "platform-engineering"],
        skills_tags=["linux", "kubernetes", "prometheus", "incident-response"],
        candidate_qualities=["calm-under-pressure", "ownership", "systems-debugging"],
        summary="Improve reliability practices for a multi-tenant infrastructure product.",
        description="You will help Amazon operate customer-facing infrastructure with better alerting, capacity planning, and incident response. The role includes on-call participation, post-incident reviews, SLO design, and reliability improvements across deployment and runtime systems. You should be able to debug distributed systems and turn repeated failures into durable fixes.",
        posted_at="2026-04-24",
        application_url="https://example.com/jobs/job-005",
    ),
    JobRecord(
        id="job-006",
        title="Developer Experience Engineer",
        company_id="company-amazon",
        location="Remote - Europe",
        work_mode="remote",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=105000, max=145000),
        profession_tags=["developer-experience", "platform-engineering"],
        skills_tags=["go", "python", "ci-cd", "documentation", "internal-tools"],
        candidate_qualities=["empathy", "technical-writing", "bias-for-action"],
        summary="Make internal platform tools easier for engineering teams to adopt and operate.",
        description="This role focuses on the developer-facing layer of Cinder's platform: CLIs, templates, docs, examples, and golden paths. You will interview engineers, remove friction from common workflows, and build tooling that makes the right production practices the easiest path. Success means teams ship services faster without losing operational discipline.",
        posted_at="2026-04-17",
        application_url="https://example.com/jobs/job-006",
    ),
    JobRecord(
        id="job-007",
        title="Machine Learning Engineer",
        company_id="company-meta",
        location="New York, NY",
        work_mode="onsite",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=180000, max=240000),
        profession_tags=["machine-learning", "search-engineering"],
        skills_tags=["python", "pytorch", "rag", "evaluation"],
        candidate_qualities=["research-judgment", "experimentation"],
        summary="Ship retrieval and ranking systems for a search-heavy product.",
        description="Meta Platforms needs an ML engineer to improve retrieval, ranking, and answer quality for a search-heavy product. You will build offline evaluation sets, run ranking experiments, optimize inference paths, and partner with product teams to understand where search quality breaks down for users. The role balances modeling work with practical production engineering.",
        posted_at="2026-04-25",
        application_url="https://example.com/jobs/job-007",
    ),
    JobRecord(
        id="job-008",
        title="Search Relevance Analyst",
        company_id="company-meta",
        location="New York, NY",
        work_mode="onsite",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=95000, max=125000),
        profession_tags=["search-relevance", "data-analysis"],
        skills_tags=["sql", "python", "experimentation", "ranking", "dashboards"],
        candidate_qualities=["curiosity", "attention-to-detail", "user-empathy"],
        summary="Analyze query behavior and help tune relevance for high-value search journeys.",
        description="You will investigate search logs, label result quality, build dashboards, and recommend changes to ranking and retrieval systems. The work sits between data analysis, product insight, and search quality operations. A good fit is comfortable with messy behavioral data and can explain relevance problems in concrete terms.",
        posted_at="2026-04-23",
        application_url="https://example.com/jobs/job-008",
    ),
    JobRecord(
        id="job-009",
        title="Backend Engineer, Retrieval APIs",
        company_id="company-meta",
        location="Remote - US",
        work_mode="remote",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=170000, max=220000),
        profession_tags=["backend-engineering", "search-engineering"],
        skills_tags=["python", "fastapi", "postgres", "vector-search", "distributed-systems"],
        candidate_qualities=["api-design", "reliability-minded", "debugging-depth"],
        summary="Build low-latency APIs for retrieval, ranking, and search experimentation.",
        description="Meta Platforms is hiring a backend engineer to own service boundaries around retrieval and ranking APIs. You will design endpoints, optimize query paths, improve observability, and support experimentation infrastructure used by ML and product teams. Experience with search, vector databases, or high-throughput APIs is useful but not required.",
        posted_at="2026-04-16",
        application_url="https://example.com/jobs/job-009",
    ),
    JobRecord(
        id="job-010",
        title="Frontend Engineer",
        company_id="company-microsoft",
        location="Remote - Europe",
        work_mode="remote",
        employment_type="contract",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=70000, max=100000),
        profession_tags=["frontend-engineering", "product-engineering"],
        skills_tags=["react", "typescript", "design-systems", "accessibility"],
        candidate_qualities=["product-sense", "attention-to-detail"],
        summary="Build polished user flows for a B2B operations dashboard.",
        description="Microsoft builds dense operational interfaces for logistics teams, and this role owns the frontend experience. You will work on React workflows, shared components, accessibility, data-heavy screens, and performance improvements. The best candidates care about small interaction details and know how to make complex software feel predictable for daily users.",
        posted_at="2026-04-20",
        application_url="https://example.com/jobs/job-010",
    ),
    JobRecord(
        id="job-011",
        title="UX Researcher, Operations Software",
        company_id="company-microsoft",
        location="London, UK",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=85000, max=115000),
        profession_tags=["ux-research", "product-design"],
        skills_tags=["interviews", "usability-testing", "journey-mapping", "synthesis"],
        candidate_qualities=["listening", "structured-synthesis", "field-research"],
        summary="Research how dispatch and operations teams use complex workflow software.",
        description="You will plan and run research with dispatchers, operations managers, and implementation teams. The work includes usability studies, workflow observation, customer interviews, and clear synthesis that shapes roadmap decisions. Microsoft needs someone who can understand operational nuance and turn field learning into product direction.",
        posted_at="2026-04-15",
        application_url="https://example.com/jobs/job-011",
    ),
    JobRecord(
        id="job-012",
        title="Implementation Consultant",
        company_id="company-microsoft",
        location="Remote - UK",
        work_mode="remote",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=80000, max=105000),
        profession_tags=["implementation", "customer-success"],
        skills_tags=["workflow-design", "sql", "training", "stakeholder-management"],
        candidate_qualities=["patience", "customer-empathy", "organization"],
        summary="Help new customers configure Microsoft workflow products around real operations needs.",
        description="This role guides customers from signed contract to a live operational rollout. You will map current workflows, configure dashboards, validate data, train users, and surface product gaps to engineering. It is a strong fit for someone who likes customer work but can also reason about systems, data, and process design.",
        posted_at="2026-04-14",
        application_url="https://example.com/jobs/job-012",
    ),
    JobRecord(
        id="job-013",
        title="Applied AI Intern",
        company_id="company-nvidia",
        location="San Francisco, CA",
        work_mode="hybrid",
        employment_type="internship",
        seniority="junior",
        salary_range=SalaryRange(currency="USD", min=35, max=50),
        profession_tags=["ai-engineering", "internship"],
        skills_tags=["python", "agents", "prompting", "evaluation"],
        candidate_qualities=["curiosity", "fast-learning"],
        summary="Prototype internal tools that help recruiters and candidates move faster.",
        description="NVIDIA is hiring an intern to help prototype applied AI tools for recruiting workflows. You will write small Python services, test prompt variants, connect tools, and summarize experiment results for the team. This is a learning-heavy role for someone who has built projects, asks precise questions, and can turn feedback into quick iterations.",
        posted_at="2026-04-24",
        application_url="https://example.com/jobs/job-013",
    ),
    JobRecord(
        id="job-014",
        title="Prompt Evaluation Specialist",
        company_id="company-nvidia",
        location="Remote - US",
        work_mode="remote",
        employment_type="contract",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=65000, max=95000),
        profession_tags=["ai-evaluation", "prompt-engineering"],
        skills_tags=["prompting", "evaluation", "spreadsheets", "quality-review"],
        candidate_qualities=["precision", "taste", "documentation"],
        summary="Design and review evaluation sets for recruiting assistant behavior.",
        description="You will create test cases, review model outputs, document failure modes, and help the team improve assistant prompts. The work requires careful reading, consistent judgment, and the ability to explain why an answer is or is not acceptable in a recruiting context. Experience with LLM evaluation or quality operations is helpful.",
        posted_at="2026-04-13",
        application_url="https://example.com/jobs/job-014",
    ),
    JobRecord(
        id="job-015",
        title="Customer Solutions Engineer",
        company_id="company-nvidia",
        location="San Francisco, CA",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=115000, max=150000),
        profession_tags=["solutions-engineering", "applied-ai"],
        skills_tags=["python", "apis", "customer-discovery", "technical-demos"],
        candidate_qualities=["communication", "adaptability", "technical-judgment"],
        summary="Build customer demos and lightweight integrations for applied AI recruiting tools.",
        description="You will partner with founders and customers to understand recruiting workflows, build demos, wire up APIs, and translate pilot feedback into product requirements. This is a hands-on technical customer role that rewards clear communication, fast prototyping, and good judgment about what should become product versus one-off support.",
        posted_at="2026-04-12",
        application_url="https://example.com/jobs/job-015",
    ),
]
