from __future__ import annotations

from app.models import CompanyRecord, JobRecord, SalaryRange


MOCK_COMPANIES: list[CompanyRecord] = [
    CompanyRecord(
        id="company-northstar",
        name="Northstar Labs",
        description="Internal automation lab building recruiting and operations agents.",
        website="https://example.com/northstar",
        industry="AI tooling",
        headquarters="Austin, TX",
        size="51-200",
        legal_name="Northstar Labs, Inc.",
        address_line1="412 E 6th St",
        address_line2="Suite 900",
        city="Austin",
        region="TX",
        postal_code="78701",
        country="US",
        po_box="PO Box 1842",
        phone="+1-512-555-0194",
        contact_email="talent@example.com",
        location="Austin, TX, US",
        latitude=30.2672,
        longitude=-97.7431,
        founded_year=2021,
        short_history="Founded by automation engineers to build internal agent systems for recruiting and operations teams.",
    ),
    CompanyRecord(
        id="company-cinder",
        name="Cinder Systems",
        description="Infrastructure company for data-heavy engineering teams.",
        website="https://example.com/cinder",
        industry="Cloud infrastructure",
        headquarters="Berlin, Germany",
        size="201-500",
        legal_name="Cinder Systems GmbH",
        address_line1="Invalidenstrasse 91",
        address_line2="Floor 4",
        city="Berlin",
        region="Berlin",
        postal_code="10115",
        country="DE",
        po_box="Postfach 110221",
        phone="+49-30-555-0148",
        contact_email="jobs@example.com",
        location="Berlin, Germany",
        latitude=52.52,
        longitude=13.405,
        founded_year=2018,
        short_history="Started as a deployment tooling consultancy and grew into a platform engineering product company.",
    ),
    CompanyRecord(
        id="company-signal-harbor",
        name="Signal Harbor",
        description="Search product company focused on retrieval and ranking quality.",
        website="https://example.com/signal-harbor",
        industry="Search",
        headquarters="New York, NY",
        size="51-200",
        legal_name="Signal Harbor Corp.",
        address_line1="225 Broadway",
        address_line2="Suite 1800",
        city="New York",
        region="NY",
        postal_code="10007",
        country="US",
        po_box="PO Box 730",
        phone="+1-212-555-0188",
        contact_email="careers@example.com",
        location="New York, NY, US",
        latitude=40.7128,
        longitude=-74.006,
        founded_year=2020,
        short_history="Formed by search infrastructure veterans to commercialize retrieval quality tooling.",
    ),
    CompanyRecord(
        id="company-maple-orbit",
        name="Maple Orbit",
        description="B2B operations dashboard for high-volume logistics teams.",
        website="https://example.com/maple-orbit",
        industry="Operations software",
        headquarters="London, UK",
        size="11-50",
        legal_name="Maple Orbit Ltd.",
        address_line1="10 Finsbury Square",
        address_line2="Unit 6B",
        city="London",
        region="England",
        postal_code="EC2A 1AF",
        country="GB",
        po_box="PO Box 28119",
        phone="+44-20-5555-0131",
        contact_email="work@example.com",
        location="London, UK",
        latitude=51.5072,
        longitude=-0.1276,
        founded_year=2022,
        short_history="Built from a logistics dashboard project into workflow software for operations teams.",
    ),
    CompanyRecord(
        id="company-juniper-peak",
        name="Juniper Peak",
        description="Applied AI studio prototyping recruiting workflow tools.",
        website="https://example.com/juniper-peak",
        industry="Applied AI",
        headquarters="San Francisco, CA",
        size="11-50",
        legal_name="Juniper Peak AI LLC",
        address_line1="548 Market St",
        address_line2="PMB 33124",
        city="San Francisco",
        region="CA",
        postal_code="94104",
        country="US",
        po_box="PO Box 33124",
        phone="+1-415-555-0162",
        contact_email="internships@example.com",
        location="San Francisco, CA, US",
        latitude=37.7749,
        longitude=-122.4194,
        founded_year=2023,
        short_history="Launched as a small applied AI studio focused on fast prototypes for recruiting teams.",
    ),
]


MOCK_JOBS: list[JobRecord] = [
    JobRecord(
        id="job-001",
        title="AI Agent Engineer",
        company_id="company-northstar",
        location="Remote - US",
        work_mode="remote",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=160000, max=210000),
        profession_tags=["ai-engineering", "backend-engineering"],
        skills_tags=["typescript", "python", "mcp", "agents", "valkey", "llm"],
        candidate_qualities=["ownership", "systems-thinking", "clear-writing"],
        summary="Build agent tooling and evaluation loops for internal recruiting workflows.",
        description="You will design and ship agent workflows that help recruiting teams source, screen, and follow up with candidates. The role covers MCP tool integration, prompt and policy design, evaluation harnesses, and production monitoring. You should be comfortable moving from a rough workflow idea to a reliable internal service used by non-engineering teams.",
        posted_at="2026-04-22",
        application_url="https://example.com/jobs/job-001",
    ),
    JobRecord(
        id="job-002",
        title="Recruiting Data Engineer",
        company_id="company-northstar",
        location="Remote - US",
        work_mode="remote",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=130000, max=170000),
        profession_tags=["data-engineering", "analytics-engineering"],
        skills_tags=["python", "sql", "dbt", "airflow", "valkey"],
        candidate_qualities=["data-quality", "stakeholder-empathy", "pragmatism"],
        summary="Build clean recruiting datasets and operational analytics for agent-assisted workflows.",
        description="Northstar Labs is hiring a data engineer to own the pipelines that feed recruiting automation products. You will model candidate, job, outreach, and interview data; build quality checks; and partner with product teams to make sure automation decisions are explainable and measurable. This is a hands-on role with room to shape data standards across the company.",
        posted_at="2026-04-21",
        application_url="https://example.com/jobs/job-002",
    ),
    JobRecord(
        id="job-003",
        title="Product Manager, Agent Workflows",
        company_id="company-northstar",
        location="Austin, TX",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=150000, max=195000),
        profession_tags=["product-management", "ai-product"],
        skills_tags=["roadmapping", "user-research", "experimentation", "analytics"],
        candidate_qualities=["structured-thinking", "customer-focus", "clear-communication"],
        summary="Lead product direction for internal recruiting agents and workflow automation.",
        description="You will define the roadmap for agent-assisted recruiting workflows, working closely with recruiters, engineers, and operations leaders. The work includes discovery, workflow mapping, launch planning, experiment design, and success metrics. A strong candidate can translate ambiguous operational pain into scoped product bets and measurable releases.",
        posted_at="2026-04-19",
        application_url="https://example.com/jobs/job-003",
    ),
    JobRecord(
        id="job-004",
        title="Platform Engineer",
        company_id="company-cinder",
        location="Berlin, Germany",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=95000, max=130000),
        profession_tags=["platform-engineering", "devops"],
        skills_tags=["go", "kubernetes", "terraform", "observability"],
        candidate_qualities=["production-ownership", "collaboration"],
        summary="Maintain platform foundations for data and automation teams.",
        description="Cinder Systems is looking for a platform engineer to improve the infrastructure used by product and data teams. You will work on Kubernetes clusters, service templates, Terraform modules, observability defaults, and incident readiness. The team values practical automation, clear runbooks, and a measured approach to production change.",
        posted_at="2026-04-18",
        application_url="https://example.com/jobs/job-004",
    ),
    JobRecord(
        id="job-005",
        title="Site Reliability Engineer",
        company_id="company-cinder",
        location="Berlin, Germany",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=125000, max=165000),
        profession_tags=["site-reliability", "platform-engineering"],
        skills_tags=["linux", "kubernetes", "prometheus", "incident-response"],
        candidate_qualities=["calm-under-pressure", "ownership", "systems-debugging"],
        summary="Improve reliability practices for a multi-tenant infrastructure product.",
        description="You will help Cinder Systems operate customer-facing infrastructure with better alerting, capacity planning, and incident response. The role includes on-call participation, post-incident reviews, SLO design, and reliability improvements across deployment and runtime systems. You should be able to debug distributed systems and turn repeated failures into durable fixes.",
        posted_at="2026-04-24",
        application_url="https://example.com/jobs/job-005",
    ),
    JobRecord(
        id="job-006",
        title="Developer Experience Engineer",
        company_id="company-cinder",
        location="Remote - Europe",
        work_mode="remote",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=105000, max=145000),
        profession_tags=["developer-experience", "platform-engineering"],
        skills_tags=["go", "python", "ci-cd", "documentation", "internal-tools"],
        candidate_qualities=["empathy", "technical-writing", "bias-for-action"],
        summary="Make internal platform tools easier for engineering teams to adopt and operate.",
        description="This role focuses on the developer-facing layer of Cinder's platform: CLIs, templates, docs, examples, and golden paths. You will interview engineers, remove friction from common workflows, and build tooling that makes the right production practices the easiest path. Success means teams ship services faster without losing operational discipline.",
        posted_at="2026-04-17",
        application_url="https://example.com/jobs/job-006",
    ),
    JobRecord(
        id="job-007",
        title="Machine Learning Engineer",
        company_id="company-signal-harbor",
        location="New York, NY",
        work_mode="onsite",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=180000, max=240000),
        profession_tags=["machine-learning", "search-engineering"],
        skills_tags=["python", "pytorch", "rag", "evaluation"],
        candidate_qualities=["research-judgment", "experimentation"],
        summary="Ship retrieval and ranking systems for a search-heavy product.",
        description="Signal Harbor needs an ML engineer to improve retrieval, ranking, and answer quality for a search-heavy product. You will build offline evaluation sets, run ranking experiments, optimize inference paths, and partner with product teams to understand where search quality breaks down for users. The role balances modeling work with practical production engineering.",
        posted_at="2026-04-25",
        application_url="https://example.com/jobs/job-007",
    ),
    JobRecord(
        id="job-008",
        title="Search Relevance Analyst",
        company_id="company-signal-harbor",
        location="New York, NY",
        work_mode="onsite",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=95000, max=125000),
        profession_tags=["search-relevance", "data-analysis"],
        skills_tags=["sql", "python", "experimentation", "ranking", "dashboards"],
        candidate_qualities=["curiosity", "attention-to-detail", "user-empathy"],
        summary="Analyze query behavior and help tune relevance for high-value search journeys.",
        description="You will investigate search logs, label result quality, build dashboards, and recommend changes to ranking and retrieval systems. The work sits between data analysis, product insight, and search quality operations. A good fit is comfortable with messy behavioral data and can explain relevance problems in concrete terms.",
        posted_at="2026-04-23",
        application_url="https://example.com/jobs/job-008",
    ),
    JobRecord(
        id="job-009",
        title="Backend Engineer, Retrieval APIs",
        company_id="company-signal-harbor",
        location="Remote - US",
        work_mode="remote",
        employment_type="full-time",
        seniority="senior",
        salary_range=SalaryRange(currency="USD", min=170000, max=220000),
        profession_tags=["backend-engineering", "search-engineering"],
        skills_tags=["python", "fastapi", "postgres", "vector-search", "distributed-systems"],
        candidate_qualities=["api-design", "reliability-minded", "debugging-depth"],
        summary="Build low-latency APIs for retrieval, ranking, and search experimentation.",
        description="Signal Harbor is hiring a backend engineer to own service boundaries around retrieval and ranking APIs. You will design endpoints, optimize query paths, improve observability, and support experimentation infrastructure used by ML and product teams. Experience with search, vector databases, or high-throughput APIs is useful but not required.",
        posted_at="2026-04-16",
        application_url="https://example.com/jobs/job-009",
    ),
    JobRecord(
        id="job-010",
        title="Frontend Engineer",
        company_id="company-maple-orbit",
        location="Remote - Europe",
        work_mode="remote",
        employment_type="contract",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=70000, max=100000),
        profession_tags=["frontend-engineering", "product-engineering"],
        skills_tags=["react", "typescript", "design-systems", "accessibility"],
        candidate_qualities=["product-sense", "attention-to-detail"],
        summary="Build polished user flows for a B2B operations dashboard.",
        description="Maple Orbit builds dense operational interfaces for logistics teams, and this role owns the frontend experience. You will work on React workflows, shared components, accessibility, data-heavy screens, and performance improvements. The best candidates care about small interaction details and know how to make complex software feel predictable for daily users.",
        posted_at="2026-04-20",
        application_url="https://example.com/jobs/job-010",
    ),
    JobRecord(
        id="job-011",
        title="UX Researcher, Operations Software",
        company_id="company-maple-orbit",
        location="London, UK",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=85000, max=115000),
        profession_tags=["ux-research", "product-design"],
        skills_tags=["interviews", "usability-testing", "journey-mapping", "synthesis"],
        candidate_qualities=["listening", "structured-synthesis", "field-research"],
        summary="Research how dispatch and operations teams use complex workflow software.",
        description="You will plan and run research with dispatchers, operations managers, and implementation teams. The work includes usability studies, workflow observation, customer interviews, and clear synthesis that shapes roadmap decisions. Maple Orbit needs someone who can understand operational nuance and turn field learning into product direction.",
        posted_at="2026-04-15",
        application_url="https://example.com/jobs/job-011",
    ),
    JobRecord(
        id="job-012",
        title="Implementation Consultant",
        company_id="company-maple-orbit",
        location="Remote - UK",
        work_mode="remote",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=80000, max=105000),
        profession_tags=["implementation", "customer-success"],
        skills_tags=["workflow-design", "sql", "training", "stakeholder-management"],
        candidate_qualities=["patience", "customer-empathy", "organization"],
        summary="Help new customers configure Maple Orbit around real operations workflows.",
        description="This role guides customers from signed contract to a live operational rollout. You will map current workflows, configure dashboards, validate data, train users, and surface product gaps to engineering. It is a strong fit for someone who likes customer work but can also reason about systems, data, and process design.",
        posted_at="2026-04-14",
        application_url="https://example.com/jobs/job-012",
    ),
    JobRecord(
        id="job-013",
        title="Applied AI Intern",
        company_id="company-juniper-peak",
        location="San Francisco, CA",
        work_mode="hybrid",
        employment_type="internship",
        seniority="junior",
        salary_range=SalaryRange(currency="USD", min=35, max=50),
        profession_tags=["ai-engineering", "internship"],
        skills_tags=["python", "agents", "prompting", "evaluation"],
        candidate_qualities=["curiosity", "fast-learning"],
        summary="Prototype internal tools that help recruiters and candidates move faster.",
        description="Juniper Peak is hiring an intern to help prototype applied AI tools for recruiting workflows. You will write small Python services, test prompt variants, connect tools, and summarize experiment results for the team. This is a learning-heavy role for someone who has built projects, asks precise questions, and can turn feedback into quick iterations.",
        posted_at="2026-04-24",
        application_url="https://example.com/jobs/job-013",
    ),
    JobRecord(
        id="job-014",
        title="Prompt Evaluation Specialist",
        company_id="company-juniper-peak",
        location="Remote - US",
        work_mode="remote",
        employment_type="contract",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=65000, max=95000),
        profession_tags=["ai-evaluation", "prompt-engineering"],
        skills_tags=["prompting", "evaluation", "spreadsheets", "quality-review"],
        candidate_qualities=["precision", "taste", "documentation"],
        summary="Design and review evaluation sets for recruiting assistant behavior.",
        description="You will create test cases, review model outputs, document failure modes, and help the team improve assistant prompts. The work requires careful reading, consistent judgment, and the ability to explain why an answer is or is not acceptable in a recruiting context. Experience with LLM evaluation or quality operations is helpful.",
        posted_at="2026-04-13",
        application_url="https://example.com/jobs/job-014",
    ),
    JobRecord(
        id="job-015",
        title="Customer Solutions Engineer",
        company_id="company-juniper-peak",
        location="San Francisco, CA",
        work_mode="hybrid",
        employment_type="full-time",
        seniority="mid",
        salary_range=SalaryRange(currency="USD", min=115000, max=150000),
        profession_tags=["solutions-engineering", "applied-ai"],
        skills_tags=["python", "apis", "customer-discovery", "technical-demos"],
        candidate_qualities=["communication", "adaptability", "technical-judgment"],
        summary="Build customer demos and lightweight integrations for applied AI recruiting tools.",
        description="You will partner with founders and customers to understand recruiting workflows, build demos, wire up APIs, and translate pilot feedback into product requirements. This is a hands-on technical customer role that rewards clear communication, fast prototyping, and good judgment about what should become product versus one-off support.",
        posted_at="2026-04-12",
        application_url="https://example.com/jobs/job-015",
    ),
]
